spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-study
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #console에 남김.
        #show_sql: true
        format_sql: true

logging.level:
  #log파일에 남김
  org.hibernate.SQL: debug
  #파라미터 바인딩 값 표시
  #org.hibernate.type: trace
